<footer class="footer">

    <p>&copy; 2026 G06 Creative Media &amp; Design</p>

    <p>
        Contact us:
        <a href="mailto:info@nextgenwebworks.com">
            info@nextgenwebworks.com
        </a>
    </p>

    <a href="https://vsuk0001.atlassian.net/jira/software/projects/CGRW/summary"
       target="_blank"
       rel="noopener noreferrer">

       Jira Board

    </a>

    <a href="https://github.com/105533624/Assignment_1"
       target="_blank"
       rel="noopener noreferrer">

       GitHub Repository

    </a>

</footer>

</body>
</html>