<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="description" content="Jobs Page">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="keywords" content="jobs, careers, web development">
    <meta name="author" content="Vansh">

    <title>NextGen Web Works - Jobs</title>

    <link rel="stylesheet" href="styles/styles.css">
</head>
<body>