 <header>

    <div class="logo">

        <img src="images/logo.png"
             alt="NextGen Web Works Logo"
             width="100">

        <div class="logo-text">
            <h1>NextGen Web Works</h1>
        </div>

    </div>

    <nav>

        <ul>
            <li><a href="index.php">Home</a></li>
            <li><a href="jobs.php">Jobs</a></li>
            <li><a href="apply.php">Apply</a></li>
            <li><a href="about.php">About Us</a></li>
        </ul>

    </nav>

</header>