<footer class="footer">
    <p>&copy; 2026 G06 Creative Media &amp; Design</p>
    <p>
        Contact us:
        <a href="mailto:info@nextgenwebworks.com" title="Email our recruitment team">
            info@nextgenwebworks.com
        </a>
    </p>
    <div class="footer-links">
        <a href="https://vsuk0001.atlassian.net/jira/software/projects/CGRW/summary" target="_blank" rel="noopener noreferrer">Jira Board</a> |
        <a href="https://github.com/105533624/project-2/tree/main" target="_blank" rel="noopener noreferrer">GitHub Repository</a>
    </div>
</footer>
